### ISSUE TITLE
STAIRS `I'm ready for question` button disabled

### ISSUE THREAD

**Issue by qiushiyan** [learlab/itell-strapi-demo#17]
![Image](https://github.com/learlab/itell-strapi-demo/assets/57017670/02fb96f7-f401-478b-8ca5-51566933f41a)

**Comment by qiushiyan** [comment]
@jchoi92k is this still happening for you?

**Comment by jchoi92k** [comment]
This wasn't happening consistently when I was testing, and I don't know how to replicate it, unfortunately.
