### ISSUE TITLE
No chunks are highlighted after submitting summary

### ISSUE THREAD

**Issue by jchoi92k** [learlab/itell-strapi-demo#23]
![Image](https://github.com/learlab/itell-strapi-demo/assets/57017670/18a2a055-a88a-4ffa-9983-ef3f787401fd)

---
@qiushiyan  Issue is persisting on my end
Tried using different browsers, resetting progress, clearing cache, etc.

![Image](https://github.com/learlab/itell-strapi-demo/assets/57017670/6cd8977a-10b2-4916-862c-8dff413aee6e)

---
Also happens with STAIRS sometimes:

![Image](https://github.com/learlab/itell-strapi-demo/assets/57017670/85ff8f58-a5b5-44f7-99f3-1f1ff0bc2edc)

Happened on Chapter 6 Page 5 with this summary:

> months according to NBER and was concentrated across Quarters 1 and 2 of 2020, real GDP dropped 9%—much larger and quicker of a drop than during the previous economic downturn, the Great Recession (2007–2009). The economy quickly bounced back, and as of Quarter 1 of 2021, real GDP had slightly surpassed the level it was at prior to the start of the pandemic. These statistics show the severity of the pandemic-induced recession, and while real GDP fully recovered, there are other ways in which the economy has not. While GDP and GDP per capita give us a rough estimate of a nation's standard of living, there are many other ways to track the health of the economy. This chapter is the building block for other chapters that explore more economic indicators such as unemployment, inflation, or interest rates, and perhaps more importantly, will explain how they are related and what causes them to rise or fall.

**Comment by scrosseye** [comment]
Happened to me as well



![Image](https://github.com/learlab/itell-strapi-demo/assets/17437369/f11c59a5-8d77-4098-843d-7e51b731d150)
