### ISSUE TITLE
Strategies discussed at beginning of chapter?

### ISSUE THREAD

**Issue by scrosseye** [learlab/itell-strapi-demo#28]
Thought I had left a note to introduce strategies to simple and rereading groups at the beginning of each of the two chapters?

Don't see the changes and do not see the issue tracked on github?

**Comment by jchoi92k** [comment]
I think this may be a cache issue. Can you try hard refreshing? I do see the notes at the beginning of the two chapters:



![Image](https://github.com/learlab/itell-strapi-demo/assets/57017670/75dbac91-526c-497e-9de0-20f100beb2b8)
